# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerator.proto\x12\x05proto\"\x1f\n\x0fGenerateRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"$\n\x10GenerateResponse\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t2N\n\rFileGenerator\x12=\n\x08Generate\x12\x16.proto.GenerateRequest\x1a\x17.proto.GenerateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERATEREQUEST']._serialized_start=26
  _globals['_GENERATEREQUEST']._serialized_end=57
  _globals['_GENERATERESPONSE']._serialized_start=59
  _globals['_GENERATERESPONSE']._serialized_end=95
  _globals['_FILEGENERATOR']._serialized_start=97
  _globals['_FILEGENERATOR']._serialized_end=175
# @@protoc_insertion_point(module_scope)
