-- DROP TABLE  teachers CASCADE ;
-- DROP TABLE  students CASCADE;
-- DROP TABLE  groups CASCADE;
-- DROP TABLE  courses CASCADE;
-- DROP TABLE  courses_groups CASCADE;
-- DROP TABLE  teachers_courses CASCADE;
