# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerator.proto\x12\x02pb\"8\n\x0fGenerateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\t.pb.MyMap\"T\n\x05MyMap\x12\x1f\n\x03map\x18\x01 \x03(\x0b\x32\x12.pb.MyMap.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x10GenerateResponse\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2F\n\rFileGenerator\x12\x35\n\x08Generate\x12\x13.pb.GenerateRequest\x1a\x14.pb.GenerateResponseB\x0fZ\rrudnWebApp/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rrudnWebApp/pb'
  _globals['_MYMAP_MAPENTRY']._options = None
  _globals['_MYMAP_MAPENTRY']._serialized_options = b'8\001'
  _globals['_GENERATEREQUEST']._serialized_start=23
  _globals['_GENERATEREQUEST']._serialized_end=79
  _globals['_MYMAP']._serialized_start=81
  _globals['_MYMAP']._serialized_end=165
  _globals['_MYMAP_MAPENTRY']._serialized_start=123
  _globals['_MYMAP_MAPENTRY']._serialized_end=165
  _globals['_GENERATERESPONSE']._serialized_start=167
  _globals['_GENERATERESPONSE']._serialized_end=219
  _globals['_FILEGENERATOR']._serialized_start=221
  _globals['_FILEGENERATOR']._serialized_end=291
# @@protoc_insertion_point(module_scope)
