CREATE TABLE table1
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table2
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table3
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table4
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table5
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table6
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table7
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table8
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table9
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table10
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table11
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table12
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table13
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table14
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table15
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table16
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table17
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table18
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table19
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table20
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table21
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table22
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table23
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table24
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table25
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table26
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table27
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table28
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table29
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table30
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table31
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table32
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table33
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table34
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table35
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table36
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table37
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table38
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table39
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table40
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table41
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table42
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table43
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table44
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table45
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table46
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table47
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table48
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table49
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table50
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table51
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table52
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table53
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
CREATE TABLE table54
(
    id     SERIAL       NOT NULL PRIMARY KEY,
    field1 VARCHAR(255) NOT NULL
);
