// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import ()

type Course struct {
	ID                int32  `json:"id"`
	Name              string `json:"name"`
	LectureHours      int32  `json:"lecture_hours"`
	LaboratoriesHours int32  `json:"laboratories_hours"`
	PractiseHours     int32  `json:"practise_hours"`
}

type CoursesGroup struct {
	CourseName string `json:"course_name"`
	GroupsID   int32  `json:"groups_id"`
}

type Group struct {
	ID     int32  `json:"id"`
	Code   string `json:"code"`
	Number int32  `json:"number"`
	Name   string `json:"name"`
}

type Student struct {
	ID       int32  `json:"id"`
	FullName string `json:"full_name"`
	GroupID  int32  `json:"group_id"`
}

type Teacher struct {
	ID         int32  `json:"id"`
	FullName   string `json:"full_name"`
	Department string `json:"department"`
}

type TeachersCourse struct {
	TeachersName string `json:"teachers_name"`
	CourseName   string `json:"course_name"`
}
