// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import ()

type Group struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Number int32  `json:"number"`
}

type Student struct {
	ID       int32  `json:"id"`
	FullName string `json:"full_name"`
	GroupID  int32  `json:"group_id"`
}

type Teacher struct {
	ID       int32  `json:"id"`
	FullName string `json:"full_name"`
	Age      int32  `json:"age"`
}

type TeachersGroup struct {
	TeachersID int32 `json:"teachers_id"`
	GroupsID   int32 `json:"groups_id"`
}

type User struct {
	ID             int32  `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	FullName       string `json:"full_name"`
	Email          string `json:"email"`
}
