// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupsCourse(ctx context.Context, arg CreateGroupsCourseParams) (CoursesGroup, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	CreateTeachersCourse(ctx context.Context, arg CreateTeachersCourseParams) (TeachersCourse, error)
	GetCourse(ctx context.Context, name string) (Course, error)
	GetGroup(ctx context.Context, name string) (Group, error)
	GetGroupsCourse(ctx context.Context, arg GetGroupsCourseParams) (CoursesGroup, error)
	GetTeacher(ctx context.Context, fullName string) (Teacher, error)
	GetTeachersCourse(ctx context.Context, arg GetTeachersCourseParams) (TeachersCourse, error)
	ListAllCourses(ctx context.Context) ([]Course, error)
	ListAllGroups(ctx context.Context) ([]Group, error)
	ListAllGroupsCourse(ctx context.Context) ([]CoursesGroup, error)
	ListAllTeachers(ctx context.Context) ([]Group, error)
	ListAllTeachersCourses(ctx context.Context) ([]TeachersCourse, error)
}

var _ Querier = (*Queries)(nil)
