// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetGroup(ctx context.Context, id int32) (Group, error)
	GetTeacher(ctx context.Context, id int32) (Teacher, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAllGroups(ctx context.Context) ([]Group, error)
	ListAllTeachers(ctx context.Context) ([]Teacher, error)
	//LIMIT $2
	ListAllTeachersGroups(ctx context.Context, id int32) ([]ListAllTeachersGroupsRow, error)
}

var _ Querier = (*Queries)(nil)
