// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: teachers.sql

package db

import (
	"context"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers (
    full_name,
    age
) VALUES (
             $1, $2
         ) RETURNING id, full_name, age
`

type CreateTeacherParams struct {
	FullName string `json:"full_name"`
	Age      int32  `json:"age"`
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, createTeacher, arg.FullName, arg.Age)
	var i Teacher
	err := row.Scan(&i.ID, &i.FullName, &i.Age)
	return i, err
}

const getTeacher = `-- name: GetTeacher :one
SELECT id, full_name, age FROM teachers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeacher(ctx context.Context, id int32) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, id)
	var i Teacher
	err := row.Scan(&i.ID, &i.FullName, &i.Age)
	return i, err
}

const listAllTeachers = `-- name: ListAllTeachers :many
SELECT id, full_name, age FROM teachers
ORDER BY id
`

func (q *Queries) ListAllTeachers(ctx context.Context) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listAllTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(&i.ID, &i.FullName, &i.Age); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
