// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: generator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileGenerator_Generate_FullMethodName = "/pb.FileGenerator/Generate"
)

// FileGeneratorClient is the client API for FileGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileGeneratorClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type fileGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewFileGeneratorClient(cc grpc.ClientConnInterface) FileGeneratorClient {
	return &fileGeneratorClient{cc}
}

func (c *fileGeneratorClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, FileGenerator_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileGeneratorServer is the server API for FileGenerator service.
// All implementations must embed UnimplementedFileGeneratorServer
// for forward compatibility
type FileGeneratorServer interface {
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedFileGeneratorServer()
}

// UnimplementedFileGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedFileGeneratorServer struct {
}

func (UnimplementedFileGeneratorServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedFileGeneratorServer) mustEmbedUnimplementedFileGeneratorServer() {}

// UnsafeFileGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileGeneratorServer will
// result in compilation errors.
type UnsafeFileGeneratorServer interface {
	mustEmbedUnimplementedFileGeneratorServer()
}

func RegisterFileGeneratorServer(s grpc.ServiceRegistrar, srv FileGeneratorServer) {
	s.RegisterService(&FileGenerator_ServiceDesc, srv)
}

func _FileGenerator_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileGeneratorServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileGenerator_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileGeneratorServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileGenerator_ServiceDesc is the grpc.ServiceDesc for FileGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileGenerator",
	HandlerType: (*FileGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _FileGenerator_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generator.proto",
}
