// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: k_w.sql

package db

import (
	"context"
)

const create_k_w = `-- name: Create_k_w :one
INSERT INTO "k_w" ("semester_or_Module",
                   "weeks_per_semester_module",
                   "type_of_educational_work",
                   "lecture_hours",
                   "laboratories_hours",
                   "practise_hours",
                   "type_of_PA_or_GIA",
                   "course_works",
                   "course_projects",
                   "course_Uch_ave_ZE_on_RUP",
                   "pr_ZE_on_RUP",
                   "NIR_ZE_by_RUP")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, "semester_or_Module", weeks_per_semester_module, type_of_educational_work, lecture_hours, laboratories_hours, practise_hours, "type_of_PA_or_GIA", course_works, course_projects, "course_Uch_ave_ZE_on_RUP", "pr_ZE_on_RUP", "NIR_ZE_by_RUP"
`

type Create_k_wParams struct {
	SemesterOrModule       string `json:"semester_or_Module"`
	WeeksPerSemesterModule int32  `json:"weeks_per_semester_module"`
	TypeOfEducationalWork  string `json:"type_of_educational_work"`
	LectureHours           int32  `json:"lecture_hours"`
	LaboratoriesHours      int32  `json:"laboratories_hours"`
	PractiseHours          int32  `json:"practise_hours"`
	TypeOfPAOrGIA          string `json:"type_of_PA_or_GIA"`
	CourseWorks            string `json:"course_works"`
	CourseProjects         string `json:"course_projects"`
	CourseUchAveZEOnRUP    string `json:"course_Uch_ave_ZE_on_RUP"`
	PrZEOnRUP              string `json:"pr_ZE_on_RUP"`
	NIRZEByRUP             string `json:"NIR_ZE_by_RUP"`
}

func (q *Queries) Create_k_w(ctx context.Context, arg Create_k_wParams) (KW, error) {
	row := q.db.QueryRow(ctx, create_k_w,
		arg.SemesterOrModule,
		arg.WeeksPerSemesterModule,
		arg.TypeOfEducationalWork,
		arg.LectureHours,
		arg.LaboratoriesHours,
		arg.PractiseHours,
		arg.TypeOfPAOrGIA,
		arg.CourseWorks,
		arg.CourseProjects,
		arg.CourseUchAveZEOnRUP,
		arg.PrZEOnRUP,
		arg.NIRZEByRUP,
	)
	var i KW
	err := row.Scan(
		&i.ID,
		&i.SemesterOrModule,
		&i.WeeksPerSemesterModule,
		&i.TypeOfEducationalWork,
		&i.LectureHours,
		&i.LaboratoriesHours,
		&i.PractiseHours,
		&i.TypeOfPAOrGIA,
		&i.CourseWorks,
		&i.CourseProjects,
		&i.CourseUchAveZEOnRUP,
		&i.PrZEOnRUP,
		&i.NIRZEByRUP,
	)
	return i, err
}

const get_k_w = `-- name: Get_k_w :one
SELECT id, "semester_or_Module", weeks_per_semester_module, type_of_educational_work, lecture_hours, laboratories_hours, practise_hours, "type_of_PA_or_GIA", course_works, course_projects, "course_Uch_ave_ZE_on_RUP", "pr_ZE_on_RUP", "NIR_ZE_by_RUP"
FROM k_w
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) Get_k_w(ctx context.Context, id int32) (KW, error) {
	row := q.db.QueryRow(ctx, get_k_w, id)
	var i KW
	err := row.Scan(
		&i.ID,
		&i.SemesterOrModule,
		&i.WeeksPerSemesterModule,
		&i.TypeOfEducationalWork,
		&i.LectureHours,
		&i.LaboratoriesHours,
		&i.PractiseHours,
		&i.TypeOfPAOrGIA,
		&i.CourseWorks,
		&i.CourseProjects,
		&i.CourseUchAveZEOnRUP,
		&i.PrZEOnRUP,
		&i.NIRZEByRUP,
	)
	return i, err
}
