// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: the_amount_of_teaching_work_of_the_teaching_staff.sql

package db

import (
	"context"
)

const create_the_amount_of_teaching_work_of_the_teaching_staff = `-- name: Create_the_amount_of_teaching_work_of_the_teaching_staff :one
INSERT INTO "the_amount_of_teaching_work_of_the_teaching_staff" (
                                                                 "lectures",
                                                                 "practice_or_Seminars",
                                                                 "Lab_works_or_Clinical_classes",
                                                                 "current_control",
                                                                 "interim_certification_PO_for_BRS",
                                                                 "registration_of_PA_results",
                                                                 "ongoing_consultations_on_the_discipline",
                                                                 "course_works",
                                                                 "course_projects",
                                                                 "educational_practice",
                                                                 "proc_pedagogical_and_pre_graduate_practices",
                                                                 "NIR",
                                                                 "practices_including_research_of_digital_magistracies",
                                                                 "reviewing_the_abstracts_of_graduate_students",
                                                                 "candidates_exam",
                                                                 "scientific_guidance",
                                                                 "the_leadership_of_the_WRC_or_the_NKR",
                                                                 "review_of_the_WRC",
                                                                 "GEK" ,
                                                                 "total")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,$20) RETURNING id, lectures, "practice_or_Seminars", "Lab_works_or_Clinical_classes", current_control, "interim_certification_PO_for_BRS", "registration_of_PA_results", ongoing_consultations_on_the_discipline, course_works, course_projects, educational_practice, proc_pedagogical_and_pre_graduate_practices, "NIR", practices_including_research_of_digital_magistracies, reviewing_the_abstracts_of_graduate_students, candidates_exam, scientific_guidance, "the_leadership_of_the_WRC_or_the_NKR", "review_of_the_WRC", "GEK", total
`

type Create_the_amount_of_teaching_work_of_the_teaching_staffParams struct {
	Lectures                                        float64 `json:"lectures"`
	PracticeOrSeminars                              float64 `json:"practice_or_Seminars"`
	LabWorksOrClinicalClasses                       float64 `json:"Lab_works_or_Clinical_classes"`
	CurrentControl                                  float64 `json:"current_control"`
	InterimCertificationPOForBRS                    float64 `json:"interim_certification_PO_for_BRS"`
	RegistrationOfPAResults                         float64 `json:"registration_of_PA_results"`
	OngoingConsultationsOnTheDiscipline             float64 `json:"ongoing_consultations_on_the_discipline"`
	CourseWorks                                     float64 `json:"course_works"`
	CourseProjects                                  float64 `json:"course_projects"`
	EducationalPractice                             float64 `json:"educational_practice"`
	ProcPedagogicalAndPreGraduatePractices          float64 `json:"proc_pedagogical_and_pre_graduate_practices"`
	NIR                                             float64 `json:"NIR"`
	PracticesIncludingResearchOfDigitalMagistracies float64 `json:"practices_including_research_of_digital_magistracies"`
	ReviewingTheAbstractsOfGraduateStudents         float64 `json:"reviewing_the_abstracts_of_graduate_students"`
	CandidatesExam                                  float64 `json:"candidates_exam"`
	ScientificGuidance                              float64 `json:"scientific_guidance"`
	TheLeadershipOfTheWRCOrTheNKR                   float64 `json:"the_leadership_of_the_WRC_or_the_NKR"`
	ReviewOfTheWRC                                  float64 `json:"review_of_the_WRC"`
	GEK                                             float64 `json:"GEK"`
	Total                                           float64 `json:"total"`
}

func (q *Queries) Create_the_amount_of_teaching_work_of_the_teaching_staff(ctx context.Context, arg Create_the_amount_of_teaching_work_of_the_teaching_staffParams) (TheAmountOfTeachingWorkOfTheTeachingStaff, error) {
	row := q.db.QueryRow(ctx, create_the_amount_of_teaching_work_of_the_teaching_staff,
		arg.Lectures,
		arg.PracticeOrSeminars,
		arg.LabWorksOrClinicalClasses,
		arg.CurrentControl,
		arg.InterimCertificationPOForBRS,
		arg.RegistrationOfPAResults,
		arg.OngoingConsultationsOnTheDiscipline,
		arg.CourseWorks,
		arg.CourseProjects,
		arg.EducationalPractice,
		arg.ProcPedagogicalAndPreGraduatePractices,
		arg.NIR,
		arg.PracticesIncludingResearchOfDigitalMagistracies,
		arg.ReviewingTheAbstractsOfGraduateStudents,
		arg.CandidatesExam,
		arg.ScientificGuidance,
		arg.TheLeadershipOfTheWRCOrTheNKR,
		arg.ReviewOfTheWRC,
		arg.GEK,
		arg.Total,
	)
	var i TheAmountOfTeachingWorkOfTheTeachingStaff
	err := row.Scan(
		&i.ID,
		&i.Lectures,
		&i.PracticeOrSeminars,
		&i.LabWorksOrClinicalClasses,
		&i.CurrentControl,
		&i.InterimCertificationPOForBRS,
		&i.RegistrationOfPAResults,
		&i.OngoingConsultationsOnTheDiscipline,
		&i.CourseWorks,
		&i.CourseProjects,
		&i.EducationalPractice,
		&i.ProcPedagogicalAndPreGraduatePractices,
		&i.NIR,
		&i.PracticesIncludingResearchOfDigitalMagistracies,
		&i.ReviewingTheAbstractsOfGraduateStudents,
		&i.CandidatesExam,
		&i.ScientificGuidance,
		&i.TheLeadershipOfTheWRCOrTheNKR,
		&i.ReviewOfTheWRC,
		&i.GEK,
		&i.Total,
	)
	return i, err
}

const get_the_amount_of_teaching_work_of_the_teaching_staff = `-- name: Get_the_amount_of_teaching_work_of_the_teaching_staff :one
SELECT id, lectures, "practice_or_Seminars", "Lab_works_or_Clinical_classes", current_control, "interim_certification_PO_for_BRS", "registration_of_PA_results", ongoing_consultations_on_the_discipline, course_works, course_projects, educational_practice, proc_pedagogical_and_pre_graduate_practices, "NIR", practices_including_research_of_digital_magistracies, reviewing_the_abstracts_of_graduate_students, candidates_exam, scientific_guidance, "the_leadership_of_the_WRC_or_the_NKR", "review_of_the_WRC", "GEK", total
FROM the_amount_of_teaching_work_of_the_teaching_staff
WHERE id = $1
LIMIT 1
`

func (q *Queries) Get_the_amount_of_teaching_work_of_the_teaching_staff(ctx context.Context, id int32) (TheAmountOfTeachingWorkOfTheTeachingStaff, error) {
	row := q.db.QueryRow(ctx, get_the_amount_of_teaching_work_of_the_teaching_staff, id)
	var i TheAmountOfTeachingWorkOfTheTeachingStaff
	err := row.Scan(
		&i.ID,
		&i.Lectures,
		&i.PracticeOrSeminars,
		&i.LabWorksOrClinicalClasses,
		&i.CurrentControl,
		&i.InterimCertificationPOForBRS,
		&i.RegistrationOfPAResults,
		&i.OngoingConsultationsOnTheDiscipline,
		&i.CourseWorks,
		&i.CourseProjects,
		&i.EducationalPractice,
		&i.ProcPedagogicalAndPreGraduatePractices,
		&i.NIR,
		&i.PracticesIncludingResearchOfDigitalMagistracies,
		&i.ReviewingTheAbstractsOfGraduateStudents,
		&i.CandidatesExam,
		&i.ScientificGuidance,
		&i.TheLeadershipOfTheWRCOrTheNKR,
		&i.ReviewOfTheWRC,
		&i.GEK,
		&i.Total,
	)
	return i, err
}
