// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: Together.sql

package db

import (
	"context"
)

const create_together = `-- name: Create_together :one
INSERT INTO "together"(program_id,
                       discipline_id,
                       group_id,
                       teacher_id,
                       k_w_id,
                       amount_id)

VALUES ($1, $2, $3, $4, $5, $6)
RETURNING program_id, discipline_id, teacher_id, group_id, k_w_id, amount_id
`

type Create_togetherParams struct {
	ProgramID    int32 `json:"program_id"`
	DisciplineID int32 `json:"discipline_id"`
	GroupID      int32 `json:"group_id"`
	TeacherID    int32 `json:"teacher_id"`
	KWID         int32 `json:"k_w_id"`
	AmountID     int32 `json:"amount_id"`
}

func (q *Queries) Create_together(ctx context.Context, arg Create_togetherParams) (Together, error) {
	row := q.db.QueryRow(ctx, create_together,
		arg.ProgramID,
		arg.DisciplineID,
		arg.GroupID,
		arg.TeacherID,
		arg.KWID,
		arg.AmountID,
	)
	var i Together
	err := row.Scan(
		&i.ProgramID,
		&i.DisciplineID,
		&i.TeacherID,
		&i.GroupID,
		&i.KWID,
		&i.AmountID,
	)
	return i, err
}
